### ISSUE TITLE
What about the release cycle

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-lessons#1111]
# :question: What about the release cycle

## :recycle: release cycle

- Major-release
  - 4 releases per year
    - XXXX[q1, q2, q3, q4]
- Minor-release
  - 1 release per 2 weeks
- Fix-patches
  - On demand

I thinking about it. And I want will to do it on automatic deploy. 

> :man: What do you say?

**Comment by VitalikL** [comment]
Added GitHub action to verify the deploy. Technically this is not a software repository but a content repository - the main focus is to ensure the correct / valid content
