### ISSUE TITLE
Repository memory overflow

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-lessons#1181]
# :construction:  What is digital-future of small-memory devices?

- How are you working with this repository?

My SSD 112Gb example...

`REPOSITORY: 1,6 Gb`

![Screenshot from 2020-01-22 08-59-02](https://user-images.githubusercontent.com/21124057/72869468-6d348000-3cf6-11ea-9369-1665e53fa10e.png)

All that me need is `1Mb for editing!`

- [ ] Who can help me to build right gitflow?

![Screenshot from 2020-01-22 09-19-14](https://user-images.githubusercontent.com/21124057/72870216-95bd7980-3cf8-11ea-8318-81be26c3ce10.png)

Maybe git-submodules is the best way(solution) for this `monolith-repository` in this problem? I think that the big size of this architecture repository is big problem for development.

## :evergreen_tree: Tree submodules

```console
➜  sabbath-school-lessons git:(stage) tree src/ru -L 1
src/ru
├── 2016-04
├── 2017-01
├── 2017-02
├── 2017-03
├── 2017-03-ay
├── 2017-04
├── 2017-04-ay
├── 2018-01
├── 2018-01-ay
├── 2018-02
├── 2018-02-ay
├── 2018-03
├── 2018-03-ay
├── 2018-04
├── 2018-04-ay
├── 2019-01
├── 2019-01-ay
├── 2019-02
├── 2019-02-ay
├── 2019-03
├── 2019-03-ay
├── 2019-04
├── 2020-01
└── info.yml
```
Every folder is submodule

`src / <Lang-SubModule>  | <Currently quater submodule (2020-01)>`

![Screenshot from 2020-01-22 09-28-37](https://user-images.githubusercontent.com/21124057/72870886-6c055200-3cfa-11ea-9956-2243b3e6d547.png)

@VitalikL Think about it. I know that isn't easy... `Travis-CI is broken now...`

**Comment by VitalikL** [comment]
Good point! Need to do something about the size of the repository now

**Comment by EzraEn1** [comment]
Hi! Sorry if this is resurrecting a dead issue, but Gitpod or GitHub Workspaces may be a solution to at least get work committed in the event that you do not have adequate hardware to store the whole repo.

**Comment by VitalikL** [comment]
Closing as we probably will archive most of the content in the future
