### ISSUE TITLE
API returns lessons with wrong dates in the "start_date", "end_date", "date" fields

### ISSUE THREAD

**Issue by Juzujka** [Adventech/sabbath-school-lessons#1530]
https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/index.json
"lessons": [
{
"title": "What Happened?",
"start_date": "**27/03/2020**",
"end_date": "**02/04/2020**",
"id": "01",
"index": "en-2021-02-01",
"path": "en/quarterlies/2021-02/lessons/01",
"full_path": "https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/lessons/01",
"cover": "https://sabbath-school.adventech.io/api/v1/images/global/2021-02/01/cover.png"
},

https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/lessons/01/index.json
"lesson": {
"title": "What Happened?",
"start_date": "**27/03/2020**",
"end_date": "**02/04/2020**",
"id": "01",
"index": "en-2021-02-01",
"path": "en/quarterlies/2021-02/lessons/01",
"full_path": "https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/lessons/01",
"cover": "https://sabbath-school.adventech.io/api/v1/images/global/2021-02/01/cover.png"
},
"days": [
{
"title": "What Happened?",
"date": "**27/03/2020**",
"id": "01",
"index": "en-2021-02-01-01",
"path": "en/quarterlies/2021-02/lessons/01/days/01",
"full_path": "https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/lessons/01/days/01",
"read_path": "en/quarterlies/2021-02/lessons/01/days/01/read",
"full_read_path": "https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-02/lessons/01/days/01/read"
},

Spain version wrong too

**Comment by VitalikL** [comment]
Thanks @Juzujka. Fixed now
