### ISSUE TITLE
FALSE Doubled LINK and Content

### ISSUE THREAD

**Issue by jGAtGithubCom** [Adventech/sabbath-school-lessons#1533]
The link
https://sabbath-school.adventech.io/de/2016-04/09/anzeichen-der-hoffnung/
is also for Saturday November 19th 2016 as for Tuesday November 22th 2016, and the content is identical, so I'm missing the content for this Tuesday.
Could you correct this?
Thanks a lot,
best regards
[sorry for my terrible English]

**Comment by VitalikL** [comment]
Thanks. Have you tried using API?

`https://sabbath-school.adventech.io/api/v1/de/quarterlies/2016-04/lessons/09/days/01/read/index.json`

**Comment by jGAtGithubCom** [comment]
Hi Vitali,

I called the web-URL

 

https://sabbath-school.adventech.io/de/2016-04/

 

and followed the links. Missing content because of the doubled links, saturday anf tuesday have identical links to content, e.g.

 

Best regards,

jGl

 

 
 

Gesendet: Mittwoch, 31. März 2021 um 00:29 Uhr
Von: "VitalikL" ***@***.***>
An: "Adventech/sabbath-school-lessons" ***@***.***>
Cc: "jGAtGithubCom" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Adventech/sabbath-school-lessons] FALSE Doubled LINK and Content (#1533)


 

Thanks. Have you tried using API?

https://sabbath-school.adventech.io/api/v1/de/quarterlies/2016-04/lessons/09/days/01/read/index.json

**Comment by VitalikL** [comment]
Closing as this issue has been fixed with the proper postfixes for the days that have the same slug
