### ISSUE TITLE
Get request returns a network error

### ISSUE THREAD

**Issue by kevoniori** [Adventech/sabbath-school-lessons#1589]
I've been trying to do API calls and I keep getting a 503 'Service Unavailable' error. Not sure if this is happening with anyone else, but I tried on your site and also using the postman application and they both returned a network error

**Comment by VitalikL** [comment]
Probably temporary outage? Here are the few API calls that are working for me:

GET `https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-03/index.json`

GET `https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-03/lessons/01/index.json`

**Comment by kevoniori** [comment]
These work, thanks much!

**Comment by kevoniori** [comment]
On further exploration, the path to the lesson comes up as a 404 and I get this error.

![Screen Shot 2021-06-27 at 10 58 50 AM](https://user-images.githubusercontent.com/86158992/123551299-ce0b8780-d736-11eb-882b-748543fa77a1.png)

**Comment by VitalikL** [comment]
@kevoniori, looks like you are forgetting `index.json` at the end the request URL

`https://sabbath-school.adventech.io/api/v1/en/quarterlies/2021-03/lessons/01/days/07/read/index.json`

**Comment by kevoniori** [comment]
Oh, yes thanks for that. I'm getting it now. It seems its an html markdown. What parser do you guys use for Swiftui development? I'm new to Swift so we've been working on an app for our church and wanted to integrate the content. I've used ink markdown parser but styling the html has been difficult
