### ISSUE TITLE
[ja] Tildes cause strikethrough in verse reference

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-lessons#1607]
![Screenshot_20210731-202114_One UI Home.jpg](https://user-images.githubusercontent.com/10376491/127738306-a36edab4-dd87-4f0b-a245-393cbc44acc2.jpg)

@VitalikL I thought about using fullwidth tildes as a workaround, but perhaps there's a solution I haven't thought of? 🤔

**Comment by VitalikL** [comment]
@imasaru Its been a while! Just wanted to see if this is still occurring? I remember we made some changes in the `ja` lesson prep

**Comment by imasaru** [comment]
Ah, I see—
Replacing tildes with dashes seems to have done the trick!

Are you putting them in via manual find and replace when copying from source material, or are they replaced on-the-fly before production?

Either way, I don't see strikethroughs anymore (checked one of this week's lessons)

Thank you! Hope all is well :-)

**Comment by VitalikL** [comment]
Yes, currently its done manually. Thank you :)
