### ISSUE TITLE
[ja] Extraneous whitespace and unformatted Ruby text in lessons

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-lessons#1612]
1. Extraneous whitespace: Japanese does not use spaces (yellow) like English, so it is OK to remove them. 

  - The line breaks are a fault of PDF formatting. They appear when copying text over line breaks that are in the source material. The same issue occurs with the PDF-version lessons of English and other Latin-alphabet languages as well.
  - Furthermore, Japanese whitespace characters are different from those of English and use different characters for them. Thus, eliminating them is just a matter of find-and-replace.

For webpage sources, copying the content as bare HTML and removing the `<p>` tags may fix the spacing issue 🤔

<details open><summary><b>Official SDA Quarterly Screenshot (click to reveal/hide)</b></summary>
<img src="https://user-images.githubusercontent.com/10376491/127738042-c36d993a-771a-4996-83eb-b85819aaf4e8.png" />
</details>

<details><summary><b>SS App Screenshot (click to reveal/hide)</b></summary>
<img src="https://user-images.githubusercontent.com/10376491/127737980-62385828-be66-416d-8d50-4b0ca1e33291.jpg" />
</details>

2. Japanese uses small characters called Ruby to sit on top of obscure Chinese text and serve as reading guides.

- The SS Reader is compatible with HTML `<ruby>` tagging, so it is OK to leave them if the source contains them.
- Depending on the source, the SS lessons may include additional Ruby for characters used in everyday life. Those lessons would be more suited for an Easy Reading edition. The Adult edition should contain only the Ruby specified in the official Japanese text.

<details open><summary><b>Official SDA Quarterly Screenshot (click to reveal/hide)</b></summary>
<img src="https://user-images.githubusercontent.com/10376491/127737851-ed0612ee-e934-48bf-a44d-ec51eac01500.png" />
</details>

<details><summary><b>SS App Screenshot (click to reveal/hide)</b></summary>
<img src="https://user-images.githubusercontent.com/10376491/127737976-368336b4-48b9-4332-86ac-5589fa134256.jpg" />
</details>

**Comment by VitalikL** [comment]
@imasaru Would you be able to check if this still an issue?

**Comment by imasaru** [comment]
I'm sorry I hadn't replied yet! Things have gotten real busy over here 🤔
