### ISSUE TITLE
Error Parsing of 1 John (maybe others)

### ISSUE THREAD

**Issue by Abishai2007** [Adventech/sabbath-school-lessons#163]
Lesson 7  of 2017 Q4 English (Sabbath and Wednesday) have references to 1 John that parse to the Gospel of John.

**Comment by VitalikL** [comment]
@Abishai2007 Yup, this is a known problem, which is fixed, but not yet deployed as I am writing bunch of unit tests for it

**Comment by Abishai2007** [comment]
Ok, thanks.

**Comment by VitalikL** [comment]
Fixed
