### ISSUE TITLE
Suggestion: Have the option to view the full chapter for context

### ISSUE THREAD

**Issue by Abishai2007** [Adventech/sabbath-school-lessons#164]
I believe that it would be good to have an option to view the full chapter of the Bible for context.
It is great to be able to view the Bible verse, but I believe context is extremely important.
A button could be added to the parsed Bible text window to show the full chapter.
Thank you for listening :)

**Comment by tkacikr** [comment]
I still miss this feature :-)

**Comment by VitalikL** [comment]
@Abishai2007 @tkacikr This is definitely a great feature to have, however the main problem is the copyright as most of Bibles do not allow it. We are trying to discuss this with GC and this feature is on our list.

**Comment by jpyperez** [comment]
Is there a way to put this feature on the bibles that copyright is OK with that?

**Comment by VitalikL** [comment]
@jpyperez Technically it is possible, but for now we are going to focus on other development priorities. But for sure, this will be re-reviewed in the future
