### ISSUE TITLE
Design: The Title and Date are very hard to see

### ISSUE THREAD

**Issue by Abishai2007** [Adventech/sabbath-school-lessons#165]
If the picture is very light it is almost impossible to see the Title and/or Date of of the current lesson.
An option would be to add a dark outline to the text, but I don't know how viable is this in the current setup.

**Comment by imasaru** [comment]
Which version of the app do you see this in? You may want to open an issue in the respective versions' repositories. 

You have already opened this one, though... @VitalikL what to do?

**Comment by Abishai2007** [comment]
I first saw this on lesson 4 of Q4 2017 on the iPad version. It is there on Android version but not as bad.

**Comment by VitalikL** [comment]
@Abishai2007 Can you provide screenshot of the issue you experiencing?
