### ISSUE TITLE
Global cover images unavailable in older lessons

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-lessons#166]
I was looking in some of the old lessons and cover images were not being shown from `images/global`, but either showing a [gray background](https://github.com/Adventech/sabbath-school-lessons/blob/9d40e063437afd8589c0a054e87d16c2664f7cca/src/en/2016-04/06/cover.png) (which is nice, but I can't see the lesson title) or [not showing one at all](https://github.com/Adventech/sabbath-school-lessons/tree/9d40e063437afd8589c0a054e87d16c2664f7cca/src/en/2016-04/01) (view in app to see).

This is definitely not priority, of course, but if the placeholders are random, i.e. there's no hand-picked selection of some sort, then it could be done easily. 

If anything, I could do it ❓

**Comment by VitalikL** [comment]
@imasaru Technically the global versions can be added to older quarterlies and will be updated during the compilation

**Comment by imasaru** [comment]
Yes. I made it sound as if I wanted to do the old approach without `global`, but you said what I meant :sweat_smile:

Use the same ones from `2017` or no?
