### ISSUE TITLE
Will there ever be a focus on the Youth Sabbath School

### ISSUE THREAD

**Issue by brh** [Adventech/sabbath-school-lessons#1780]
The youth sabbath school lesson Teens all the way down to Primary lacks focus from this app as well as from the publishers. The PDF from the publisher is really unprintable (for standard printers) and this app just publish the PDF it seems. This probably isn't the right place for it, but your teams seems to have some inroads to GC. They need to change the format! Could it be possible that we are able the type in the PDF that they currently have? Or you reformat it that they youth can actually write in their lessons?

**Comment by VitalikL** [comment]
Closing as this will be part of the newer curriculum that is coming out in 2025 - Alive in Jesus. The designers of the layout are currently considering providing `mobile` option, which will be native in the app.
