### ISSUE TITLE
Problem in groupings of lessons

### ISSUE THREAD

**Issue by toak** [Adventech/sabbath-school-lessons#1830]
I introduced grouping in #1821 for German/Deutsch

Unfortunately the yellow one is grouped wrong (should be under imWort)

![IMG_63837982DC53-1](https://user-images.githubusercontent.com/1171778/175289311-15c62b84-71ed-4a61-adc6-c625800515b2.jpeg)

There is only one under imWort, while there are already 4.

Same here: https://sabbath-school.adventech.io/de also the see all does not work correctly.

**Comment by VitalikL** [comment]
Yup, I will run the backend portion soon to make it backward compatible

**Comment by VitalikL** [comment]
Closing as it was fixed
