### ISSUE TITLE
Network Call issue in SwiftUI App

### ISSUE THREAD

**Issue by kevoniori** [Adventech/sabbath-school-lessons#1964]
Not sure why this happens, but whenever I try to use the "quarterly_group" data from the JSON, nothing displays in my View even if I'm not using the parameter. I can see from my console that the network call is successful, but nothing displays. I have a screenshot of my data model with and without the "quarterly group variables" & also a screenshot with the results. When I comment it out, the view shows my quarterly lists perfectly, but when I try to include it, nothing shows. What I really want to accomplish is filter out the list to only include Quarterlies from the "Standard Adult" Group

**Data Model with the quarterly_group variable**

![Screen Shot 2022-10-20 at 1 43 05 PM](https://user-images.githubusercontent.com/86158992/197032625-2092a89d-303d-472f-8fd6-8456fffb8ee7.png)

**Result in the View**

![Screen Shot 2022-10-20 at 1 43 15 PM](https://user-images.githubusercontent.com/86158992/197032860-ba930aa1-a423-45ab-9b98-9871140ab208.png)

**Data Model with the quarterly_group variable Commented out**

![Screen Shot 2022-10-20 at 1 50 18 PM](https://user-images.githubusercontent.com/86158992/197033011-5c579ff7-050b-452c-a63d-4a245b086bf8.png)

**Result in View**
![Screen Shot 2022-10-20 at 1 43 39 PM](https://user-images.githubusercontent.com/86158992/197033082-c083fef9-8223-44ee-b118-7133be2dd570.png)

**My network call code**
![Screen Shot 2022-10-20 at 1 43 54 PM](https://user-images.githubusercontent.com/86158992/197033146-9ee82208-72b8-41d6-9278-ca1c4bf8a4e3.png)

**Comment by kevoniori** [comment]
Upon further testing, it seems as if there is a problem when it comes to using nested objects, or am I doing something wrong?

**Comment by VitalikL** [comment]
@kevoniori have you checked the iOS repo on the implementation details? https://github.com/Adventech/sabbath-school-ios
