### ISSUE TITLE
Comments section (#510 Android issue)

### ISSUE THREAD

**Issue by jpyperez** [Adventech/sabbath-school-lessons#2067]
Hello @VitalikL , I saw this comment on Android app issues, and it could be possible to do this in here?

> Firstly, thanks for this amazing app, could you add a comments section for every day. (from @jucian0)

I don't know how to run the deploy.js to test locally, I'll type here what I think about it:

In this session (line 741) maybe it could be added:
```
if (donationNotice[info.language] && (/^src\/(en|de|es)\/2020-02(-er|-cq)?\/(07|08|11|13)/img.test(dayId))) {
  read.content = donationNotice[info.language] + read.content;
  resultRead = "\n\n" + donationNotice[info.language] + "\n\n" + resultRead;
}

read.content = read.content + "\n\n`Note`";

if (/src\/([a-z]{2,3})\/2023-01/img.test(dayId)) {
  let disclaimer = "<p><small>Disclaimer: Contents of these lessons are not intended to be financial advice but is general commentary based on biblical principles. The reader is encouraged to seek competent professional advice which will suit their particular personal situation.</small></p>"
  read.content = read.content + disclaimer;
  resultRead = `\n\n${disclaimer}\n\n${resultRead}`;
}
```

I don't know if this \`Note\` will create a "answer section" like happens in the lesson text.

I think this is not the optimal approach because of the translation to other languages... But if someone knows how to better improve it, it would help a lot. 

Thanks and God bless you.

**Comment by VitalikL** [comment]
@jpyperez Yes, similar approach can work, however this is the question that we will have to ask GC, as we do not want to make it too different from the actual lesson.
