### ISSUE TITLE
Docker or ./run.sh not working

### ISSUE THREAD

**Issue by RafaelPlantard** [Adventech/sabbath-school-lessons#2194]
<img width="1299" alt="image" src="https://github.com/Adventech/sabbath-school-lessons/assets/5968478/dcfee2bc-0628-4c32-8324-d134db0d6643">

**Comment by RafaelPlantard** [comment]
Unable to find image 'adventech-ss:latest' locally
docker: Error response from daemon: pull access denied for adventech-ss, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by VitalikL** [comment]
@RafaelPlantard Did you run the command to build docker image?
