### ISSUE TITLE
Android Manual Update

### ISSUE THREAD

**Issue by Burkifa23** [Adventech/sabbath-school-lessons#2208]
Hello @VitalikL,
I have heard Android users asking why the lesson is not yet uploaded yet on IOS devices it is there. I figured out later that if you open a lesson that has not yet been uploaded, later on when that lesson is uploaded, on IOS devices you can reload and get it by scrolling down and holding while on Android devices you cannot. Is there a way we can fix this issue? 
Probably enabling Android devices the same option of manually reloading in order to update the lesson.

**Comment by TinasheMzondiwa** [comment]
This is fixed in https://github.com/Adventech/sabbath-school-android/pull/702
