### ISSUE TITLE
Audios from third quarter 2023 not playing

### ISSUE THREAD

**Issue by RafaelPlantard** [Adventech/sabbath-school-lessons#2227]
The audio isn't playing neither downloading in iOS app. I've seen the audio.yml and the reason possibly is because of spaces in the name of the link. I'll try to add some scapes characters to solve it. But maybe this could be done in the iOS app when resolving the urls.

**Comment by VitalikL** [comment]
Thanks @RafaelPlantard , actually the quotes got stripped by the `audio aggregator` GH action, which is fixed now. Thank you anyways!
