### ISSUE TITLE
Need help to create pull request from fork to this repo

### ISSUE THREAD

**Issue by KeyJoo** [Adventech/sabbath-school-lessons#232]
Hi, I need help. I created [this merge branch](https://github.com/TPC-club/sabbath-school-lessons/pull/3/commits). And I want to send all 12 commints in 1 commit to **stage branch** in this repository. But my experience in git so little... Help me please.
V.

**Comment by AlmaBosnic** [comment]
I think that somebody from Adventech team will resolve your problem, but if you need guide for future work here is it. 
[How To Guide.docx](https://github.com/Adventech/sabbath-school-lessons/files/1690459/How.To.Guide.docx)
It is written by Jared Martin.

**Comment by VitalikL** [comment]
@KeyJoo This commit has already been merged, if you need to add additional changes you just simply need to create new PR

**Comment by imasaru** [comment]
@KeyJoo The official lesson contribution guide is [here](https://medium.com/p/https-medium-com-imasaru-how-to-contribute-to-adventech-6818aaca56c7).

**Comment by KeyJoo** [comment]
@AlmaBosnic, @VitalikL, @imasaru - thank you for yours answers.

**Comment by KeyJoo** [comment]
@VitalikL, are you do it work twice?

**Comment by imasaru** [comment]
@KeyJoo He did the 6th week of AY. Is that what you did?

**Comment by KeyJoo** [comment]
@imasaru Before he did [ru/2018-01/06](https://github.com/Adventech/sabbath-school-lessons/commit/3953bf9316f5da8ecde7c9f42f61dffe2b456b66) /committed **20 hours ago**/
but [/TPC-club..ru/2018](https://github.com/TPC-club/sabbath-school-lessons/pull/3/commits) /KeyJoo merged 12 commits into stage from RU/2018_01_W06 **2 days ago**/

It turns out that I did not need any work?

**Comment by imasaru** [comment]
@KeyJoo I don't quite understand either... It doesn't look like @VitalikL overwrote what you did because the files that were edited, according to the diffs, look like the placeholders we normally put.
