### ISSUE TITLE
Redeploy src/de/2022-01-qc/iv until now

### ISSUE THREAD

**Issue by toak** [Adventech/sabbath-school-lessons#2504]
I recently updates the descriptions, as they have been the same for all qc/iv lessons. Please redeploy all qc/iv starting wirh src/de/2022-01-qc

**Comment by VitalikL** [comment]
Thanks @toak , i will do it tomorrow. To optimize our deployment only targets current quarter and next quarter if we are few weeks away from it, hence the changes for old lessons were not applied.

**Comment by toak** [comment]
@VitalikL seems it's still the old content that is deployed

**Comment by VitalikL** [comment]
@toak sorry for the delay, it should be up now. Let me know if you experience any issue

**Comment by toak** [comment]
not yet...
<img width="1335" alt="image" src="https://github.com/Adventech/sabbath-school-lessons/assets/1171778/5c397014-c721-4be5-8240-391a316f37b4">

**Comment by VitalikL** [comment]
@toak probably related to the in-browser cache. Here is what I see.

![Screen Shot 2024-01-11 at 8 23 13 PM](https://github.com/Adventech/sabbath-school-lessons/assets/4108258/169022e6-cfb9-4dd3-9f67-87e37802f8ff)

**Comment by toak** [comment]
that's a fact! Thanks to much!
