### ISSUE TITLE
Adding Bogenhofen Media

### ISSUE THREAD

**Issue by andrucha97** [Adventech/sabbath-school-lessons#2540]
One of the Media Team Members of Bogenhofen got in touch with me. They asked if it is possible to add their Sabbath-School Lessons Media to our platform.

Video:
https://www.youtube.com/watch?v=sJ9mOS298HA&t=247s

Audio:
https://open.spotify.com/show/5Jyw78hHLjpW4YcNy5PjH2?si=79226fd68d43452b

They will cooperate with us. So we can tell them which file format we need.

Questions:

- Do we need to prepare something before adding this input?
- Where can Bogenhofen upload these files?
- Which code do we have to update 
    - https://github.com/Adventech/sabbath-school-lessons/blob/stage/src/de/2024-01/video.yml
    - Audio file is missing: https://github.com/Adventech/sabbath-school-lessons/blob/stage/src/en/2024-01/audio.yml
    - Do we need to add it into this file?: https://github.com/Adventech/sabbath-school-lessons/blob/stage/runners/content-aggregator/video.js
    - Do we need to add it also for audio into this file: https://github.com/Adventech/sabbath-school-lessons/blob/stage/runners/content-downloader/download-audio.js

I will send this Issue to Bogenhofen so they can see the Project status.

**Comment by arturgossen1990** [comment]
Hi, first of all, thank you for using our videos. You are super fast! That's great. But I have one more question:

I have noticed that iOS devices, at least the smartphones, only play the audio. Videos are not visible. Is there anything I need to be aware of, or is it not yet released?

**Comment by VitalikL** [comment]
> Hi, first of all, thank you for using our videos. You are super fast! That's great. But I have one more question:
> 
> I have noticed that iOS devices, at least the smartphones, only play the audio. Videos are not visible. Is there anything I need to be aware of, or is it not yet released?

You are right, there is an issue affecting certain iOS devices due to missing video codec. We will reupload with the correct codec soon.

**Comment by VitalikL** [comment]
Hi @arturgossen1990 we have resolved the issue with the video coded on iOS devices. Can you please check on your end if videos are playing correctly.

**Comment by arturgossen1990** [comment]
> Hi @arturgossen1990 we have resolved the issue with the video coded on iOS devices. Can you please check on your end if videos are playing correctly.

Yes! Everything is fine!! Thank you!

**Comment by VitalikL** [comment]
Awesome!

**Comment by andrucha97** [comment]
@VitalikL sorry if I ask after the Issue is closed.

1. Do the Video Links are pasted manual into the download file? @arturgossen1990 said that their videos are uploaded every Monday. So it would be possible that the newest Video is added on the next day?!
2. Do we want to add the audio files? I think that @arturgossen1990 could upload these on one of their server or if we can give theme some access they could upload these files.


And thanks for fixing the Video Issue on iOS. :)

**Comment by arturgossen1990** [comment]
For me, it's completely fine if the videos only appear the following day. We don't have a cloud, so it would be great if we could receive something provided by you. 
thanks again for your absolut important work!!

**Comment by VitalikL** [comment]
Hi @andrucha97 and @arturgossen1990 ,

1. Yes the videos will be added the following day, and the `video.yml` will be updated automatically. In addition the algorithm checks for up to 2 weeks ahead, so in case if you have video uploaded earlier it will grab that too.
2. That would be good. The only question i have if the audio file is the same as audio from the video file? Because we can automatically take the audio track and add as audio for the lesson. @

**Comment by arturgossen1990** [comment]
No, the audio is different. We make a proper intro and outro for podcast listeners.

**Comment by VitalikL** [comment]
@arturgossen1990 Do you upload it to any other podcast service other than Spotify?

**Comment by arturgossen1990** [comment]
Atually, we upload everything via podigee.com, and it distributes it to Spotify, Amazon Music, and Apple Music. Does that help?

**Comment by VitalikL** [comment]
Thanks @arturgossen1990 . That helps, we will utilize Podigee RSS feed to continuously download and add audios to the app.
