### ISSUE TITLE
Marcação difere da versão mobile para web.

### ISSUE THREAD

**Issue by j7info** [Adventech/sabbath-school-lessons#2629]
Recentemente descobri a versão web, e achei incrível, porém quando fui estudar, fiz todas as marcações, porém quando fui conferir no celular as marcações não conferiam as mesmas palavras que a versão web. Depois destaquei na versão mobile, porem quando conferi na web, tambem ficaram erradas.  Estou muito feliz com a qualidade da aplicação, mas se puderem observar esse detalhe e ajustar, seria melhor ainda.
![image](https://github.com/Adventech/sabbath-school-lessons/assets/15069082/93106cb8-410f-43cb-ab1f-41c4144b1fd5)

**Comment by jpyperez** [comment]
Ola @j7info, se tu fizer no celular, fechar e abrir novamente, a marcação permanece no mesmo local?
Consegue relogar (sair do login e entrar novamente) e depois fazer novas marcações e ver se o problema ocorre?
Lembro disso ter acontecido há muitos anos, e atualmente vi que está funcionando bem (pelo menos do meu lado).
Última pergunta... seu login é via google?

**Comment by j7info** [comment]
Me desculpe, agora que eu fui ver. Mas devo salientar que o problema já foi resolvido. Muito grato à equipe de desenvolvimento.

**Comment by jpyperez** [comment]
@VitalikL , as @j7info said, it was already solved and you can close this issue.
