### ISSUE TITLE
Error: Cannot find module 'optimist' in create.js.

### ISSUE THREAD

**Issue by Burkifa23** [Adventech/sabbath-school-lessons#2971]
Greetings @VitalikL  and everyone reading this issue.
I hope you're well.
I've been unable to create a new lesson for the past two weeks.

### Explanation:
---
I ran the normal node create.js
`node create.js -s "29/06/2024" -l "kin" -q "2024-03" -c 14 -t "Igitabo cya Mariko"  -d "Uhereye mu itangiriro ry'igitabo cya Mariko, bigaragara ko umusomyi azi uwo Yesu ari we. Mesiya, Umwana w'Imana (Mariko 1:1). "  -h "Nyakanga-Kanama-Nzeri 2024" -u false -i false`

Unlike other times I received an error: `Error: Cannot find module 'optimist'`
Examining the create.js on the second line, behold `var argv = require("optimist")`. 

The prior issue by @toak stated `Blocked to create new lessons using create.js script`  which I was also experiencing. I also checked whether `"@Adventech/bible-tools"` was removed and it was. 

I tried forking it several times even on different devices, but still got the same problem. 
I received other errors while cloning the repo using GitHub desktop and Git Bash.
`error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)`
`error: 4556 bytes of body are still expected`
`fetch-pack: unexpected disconnect while reading sideband packet`
`fatal: early EOF`
`fatal: fetch-pack: invalid index-pack output`
I experienced the same thing cloning the repo uncompressed.

## Short Demand:
---
Can someone run node create.js. I will supply them with the markdown files for kin for this quarter.
`node create.js -s "29/06/2024" -l "kin" -q "2024-03" -c 14 -t "Igitabo cya Mariko"  -d "Uhereye mu itangiriro ry'igitabo cya Mariko, bigaragara ko umusomyi azi uwo Yesu ari we. Mesiya, Umwana w'Imana (Mariko 1:1). "  -h "Nyakanga-Kanama-Nzeri 2024" -u false -i false`

#### Alternative:
---
@VitalikL should I create each file by file? Or should I supply you with the markdown files for kin for this quarter?
Any help would be greatly appreciated.

**Comment by VitalikL** [comment]
Hi @Burkifa23 ! As discussed, it appears that your local setup is missing `optimist` library, which can be solved by installing it locally using this command: `npm install optimist`
