### ISSUE TITLE
Bible

### ISSUE THREAD

**Issue by KitchM** [Adventech/sabbath-school-lessons#3194]
The website at https://adventech.io/sabbath-school/ shows a smartphone part way down the page with a Bible open in the display.  Where does one get that Bible?

Thanks.

**Comment by jpyperez** [comment]
Hello @KitchM, if you mean this one: 
![imagem](https://github.com/user-attachments/assets/ec485cac-ae56-4e26-a2ef-7ae27bb5256d)
you just need to click on the verse link and the verse bible will open.

**Comment by KitchM** [comment]
Yes, I do mean that one.

But what I want is the Bible on my tablet.  I just want the Bible.  How do I get that?

-- 
 Secured with Tuta Mail: 
 https://tuta.com/free-email


Dec 7, 2024, 16:13 by ***@***.***:

**Comment by VitalikL** [comment]
@KitchM We are not the Bible app, so the Bible are integrated into the app content to look up the references

**Comment by KitchM** [comment]
So where did you get that Bible part?  I noticed it had NASB included.  That's usually extra cost, and not at all available on many.

-- 
 Secured with Tuta Mail: 
 https://tuta.com/free-email


Dec 10, 2024, 14:03 by ***@***.***:

**Comment by jpyperez** [comment]
@KitchM , for bible only, I recommend the bible from YouVersion (https://www.youversion.com/the-bible-app/), there has the NASB1995 and NASB2020

**Comment by VitalikL** [comment]
@KitchM we have copyright permissions for the Bibles that we use. That is why none of the text for the Bibles are OpenSource

**Comment by KitchM** [comment]
Just to clarify for you....

My understanding of the programming should be that it is always best to be open source and freely available to all.  The problem would be that we need quality software for all platforms.  For instance, AndBible is the current best for those suffering under the restrictions of the Android OS, but sadly it does not work on other platforms.

With that said, the issue and reality of some Bible versions is that sometimes we must pay for the version we wish to incorporate into our Bible software package.  If that is how it is, then so be it.  I had already assumed that someone had paid for the NASB.  But even being able to get in into the software in the first place is key.  That you've done it was what made the inquiry necessary in the first place.

Thank you anyway.

-- 
 Secured with Tuta Mail: 
 https://tuta.com/free-email


Dec 11, 2024, 17:36 by ***@***.***:
