### ISSUE TITLE
Easy reading overriding normal edition

### ISSUE THREAD

**Issue by miking7** [Adventech/sabbath-school-lessons#373]
This quarter, only the adult and CQ editions are showing up in the app (iphone, English language). (The Easy reading edition is missing from the list of options), but when the adult edition is selected, the easy reading edition text is what comes up - ie it seems to be overriding the adult edition contents).

**Comment by miking7** [comment]
(At first I thought there were editorial mistakes with the lesson, but when I checked the .md files I realised it was the ER edition that was showing. The . md content for the main adult English lesson is correct, but it's just not coming through to the app. 
(I haven't looked close enough to the app structure to understand if this is a compilation issue, an API issue, or an app issue.)

**Comment by VitalikL** [comment]
@miking7 This is strange. I just checked on my iPhone I can see all three - Adult, ER and CQ. At the moment Adult and ER have the same cover (will update shortly), but Adult is always displayed at the top of the quarterly screen. The ER is 2nd with title "Get Ready to Meet Jesus"

**Comment by VitalikL** [comment]
@miking7 Perhaps you can post screenshot here and / or try forcing the latest content unto the app, by either switch language to different one and back or reinstalling the app.

**Comment by miking7** [comment]
Thanks @VitalikL.  I just tried switching language, then reinstalling the app, but still getting the same result. Screenshots attached. (As you can see it's only affecting this quarter's lessons).

![Image](https://i.imgur.com/XjAwAev.jpg)

![Image](https://i.imgur.com/sXfu2Vo.jpg)

![Image](https://i.imgur.com/c2VE2OZ.jpg)

![Image](https://i.imgur.com/hwl8wgc.jpg)

**Comment by VitalikL** [comment]
@miking7 "Get Ready to Meet Jesus" is Easy Reading edition and therefore displayed 2nd. The first option, "Preparation for the End Time" is regular Adult version.

**Comment by miking7** [comment]
Thanks @VItalikL. Not sure how I missed something so simple... except that this first option looks different from all the other options and I completely missed it this quarter  :-) - maybe since it looks a bit more like a heading or banner.
Maybe it was because I'm so used to using the next (week selection) screen where the first option (which also looks different) has a different function of jumping straight to today. 
Sorry to have troubled you.
