### ISSUE TITLE
Old Bible parser .md.bible files exist

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-lessons#383]
@VitalikL What do we do with these? Do you plan to keep them for historical reference?

![image](https://user-images.githubusercontent.com/10376491/38784403-f545bf90-40d6-11e8-8f82-af337840284b.png)

**Comment by imasaru** [comment]
@VitalikL what would you want to do with them?

**Comment by VitalikL** [comment]
@imasaru We would just need to delete them.

**Comment by imasaru** [comment]
@VitalikL Closed?
