### ISSUE TITLE
Show Friday Lesson when pressing "Read" button

### ISSUE THREAD

**Issue by clope031** [Adventech/sabbath-school-lessons#418]
I got some feedback from a user that recommended to show the Friday lesson when pressing the Read button. 

Currently for lessons that have teacher comments if they press the read button they will get the Teacher Comments page instead of the Friday lesson.

**Comment by VitalikL** [comment]
@imasaru @clope031 Actually Android version will jump on Monday's lesson as people likely are in church and going over the lesson

**Comment by clope031** [comment]
@imasaru she is using iOS

**Comment by VitalikL** [comment]
Implemented and pending deploy for the App Store

**Comment by imasaru** [comment]
@VitalikL Is this issue resolved? :smile:

**Comment by VitalikL** [comment]
👍 @imasaru
