### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by batarian71** [Adventech/sabbath-school-lessons#442]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by VitalikL** [comment]
Thanks @batarian71 for offering your help, which we most certainly welcome. Do you have a portfolio I can take a look at?

**Comment by batarian71** [comment]
You can visit the my github profil. The logos I've made are there.

**Comment by VitalikL** [comment]
Thanks @batarian71 I will take a look
