### ISSUE TITLE
Advise the way to reorganize the project using Docker

### ISSUE THREAD

**Issue by Vlad-Pavlychief** [Adventech/sabbath-school-lessons#554]
# Advise the way to reorganize the project using Docker

Will the process of checking the performance of tests on [Travis/CI](https://travis-ci.org/Adventech/sabbath-school-lessons/builds?from=KeyJoo) accelerate when using the **technology of Dockerization?**

For each language to make a separate image?

## Image storage?
- in the :cloud: cloud decision of the docker?

## Building
- :dart: How to later include the images of the **Docker** in the assembly of the entire project

## :warning: Attention

- :memo: Please write some recommendations. 
- :factory:  Or take part in the development of the project. 
- :+1: We will be happy to joint participation.
- It's all :cool:

**Comment by imasaru** [comment]
I've never used Docker before, but have always interested in it.

It looks 🆒

**Comment by VitalikL** [comment]
Great idea.

**Comment by merlin-zaraza** [comment]
@KeyJoo what you want to achieve with dockers?

**Comment by KeyJoo** [comment]
> @KeyJoo what you want to achieve with dockers?

:ru: **RU**

## RUS
_Попытка ответить на вопрос по Docker-container._

Предполагаю, что ты меня поймёшь. Была задумка(предложение), чтобы имеющийся монолит раздробить на кусочки: в частности по языковым пакетам, а то лишнюю инфу на SSD не хочется хранить (а весь репо занимал на тот момент 120Мб)

---

### Как я себе это представлял

- на каждый язык - отдельный контейнер
- в приложении при необходимости иметь несколько языков (выбранный догружается при подключенном интернете)

---

:gb: **EN**

## ENG

[See here](https://translate.google.com/#view=home&op=translate&sl=ru&tl=en&text=%D0%9F%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D0%B0%20%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B8%D1%82%D1%8C%20%D0%BD%D0%B0%20%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%20%D0%BF%D0%BE%20Docker-container._%0A%0A%D0%9F%D1%80%D0%B5%D0%B4%D0%BF%D0%BE%D0%BB%D0%B0%D0%B3%D0%B0%D1%8E%2C%20%D1%87%D1%82%D0%BE%20%D1%82%D1%8B%20%D0%BC%D0%B5%D0%BD%D1%8F%20%D0%BF%D0%BE%D0%B9%D0%BC%D1%91%D1%88%D1%8C.%20%D0%91%D1%8B%D0%BB%D0%B0%20%D0%B7%D0%B0%D0%B4%D1%83%D0%BC%D0%BA%D0%B0(%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5)%2C%20%D1%87%D1%82%D0%BE%D0%B1%D1%8B%20%D0%B8%D0%BC%D0%B5%D1%8E%D1%89%D0%B8%D0%B9%D1%81%D1%8F%20%D0%BC%D0%BE%D0%BD%D0%BE%D0%BB%D0%B8%D1%82%20%D1%80%D0%B0%D0%B7%D0%B4%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D1%8C%20%D0%BD%D0%B0%20%D0%BA%D1%83%D1%81%D0%BE%D1%87%D0%BA%D0%B8%3A%20%D0%B2%20%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8%20%D0%BF%D0%BE%20%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2%D1%8B%D0%BC%20%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0%D0%BC%2C%20%D0%B0%20%D1%82%D0%BE%20%D0%BB%D0%B8%D1%88%D0%BD%D1%8E%D1%8E%20%D0%B8%D0%BD%D1%84%D1%83%20%D0%BD%D0%B0%20SSD%20%D0%BD%D0%B5%20%D1%85%D0%BE%D1%87%D0%B5%D1%82%D1%81%D1%8F%20%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D1%8C%20(%D0%B0%20%D0%B2%D0%B5%D1%81%D1%8C%20%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9%20%D0%B7%D0%B0%D0%BD%D0%B8%D0%BC%D0%B0%D0%BB%20%D0%BD%D0%B0%20%D1%82%D0%BE%D1%82%20%D0%BC%D0%BE%D0%BC%D0%B5%D0%BD%D1%82%20120%D0%9C%D0%B1)%0A%0A---%0A%0A%D0%9A%D0%B0%D0%BA%20%D1%8F%20%D1%81%D0%B5%D0%B1%D0%B5%20%D1%8D%D1%82%D0%BE%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%BB%0A%0A-%20%D0%BD%D0%B0%20%D0%BA%D0%B0%D0%B6%D0%B4%D1%8B%D0%B9%20%D1%8F%D0%B7%D1%8B%D0%BA%20-%20%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%0A-%20%D0%B2%20%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%BF%D1%80%D0%B8%20%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8%20%D0%B8%D0%BC%D0%B5%D1%82%D1%8C%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2%20(%D0%B2%D1%8B%D0%B1%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9%20%D0%B4%D0%BE%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D1%80%D0%B8%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82%D0%B5))

**Comment by merlin-zaraza** [comment]
@KeyJoo для этого больше подходит [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Тоесть каждый языковый пакет выноситься в отдельный репозиторий (субмодуль). Главный репозиторий хранит только ссылки на субмодули. Подгружаешь то что нужно.
Не вижу смысла в докере т.к. он не для этого.

**Comment by VitalikL** [comment]
@merlin-zaraza В принципе можно докернизировать весь проект чтобы облегчить тестирование и сделать намного удобнее запуск на локалке - сами уроки и API для тестирования мобильного приложения

@KeyJoo Согласен с @merlin-zaraza разбивать на контейнеры по языкам это не совсем правильно. 

Решить проблему с большим размером репы поможет либо частичный чекаут (https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934) - для клиентов / разработчиков либо архивирование самого репозитория - а вообще пока до 1Гб не набралось не так страшно

**Comment by imasaru** [comment]
Haha, Теперь я знаю, как сказать «agree with» на русский. Весело.

@VitalikL Мне нравится идея частичной чекаут, особенно потому, что все больше людей делают небольшие взносы (например, корейский!)

Может быть, мы сможем решить проблему без большего количества dependencies? Я слышал, что репозиторий с субмодулиложная, но, может быть, это хорошо?

** с помощью Google Translate

**Comment by VitalikL** [comment]
@imasaru 😄 I just noticed this comment. Technically, looks like we might just archive big portion of quarterlies on a regular basis, since they are hardly gets changed. This could be a part of archive repo, that would be for reference mostly.

**Comment by Vlad-Pavlychief** [comment]
@VitalikL 

> а вообще пока до 1Гб не набралось не так страшно

imho: каждые 100Мб очень драгоценны для ssd. Ок, тему можно закрыть.

**Comment by vovs03** [comment]
# :gift_heart: Solved
> Решить проблему с большим размером репы поможет либо частичный чекаут (https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934) - для клиентов / разработчиков либо архивирование самого репозитория - а вообще пока до 1Гб не набралось не так страшно

- [x] Мне помогло такое решение: [https://unix.stackexchange.com/questions/233327/is-it-possible-to-clone-only-part-of-a-git-project](https://unix.stackexchange.com/questions/233327/is-it-possible-to-clone-only-part-of-a-git-project)
