### ISSUE TITLE
Adding new quarterly using create.js ru/2019-01

### ISSUE THREAD

**Issue by KeyJoo** [Adventech/sabbath-school-lessons#676]
# Adding new quarterly using create.js 

- [ ] ru/2019-01

I tryed creat new quarterly, but I have some errors:

Started this:
- `node --version`
  - `v8.10.0`
- `/usr/local/bin/node ./create.js -s [29/12/2018] -l [ru] -q [2019-01] -c [13] -t [Книга Откровение] -d [Написанная апостолом Иоанном книга Откровение изображает деяния Иисуса на небесах и на земле с момента Его вознесения, во время Его пришествия и после него.] -h [1й квартал 2019г.] -u [true] -i [true]`

**Comment by VitalikL** [comment]
@KeyJoo What does your error say?
