### ISSUE TITLE
 How is the connection between the repository and the domain?

### ISSUE THREAD

**Issue by KeyJoo** [Adventech/sabbath-school-lessons#749]
# How is the connection between the repository and the domain: sabbath-school.adventech.io ?

[domain](https://sabbath-school.adventech.io/ru/)

1. I still do not understand the mechanism of how the data from this repository are synchronized with the domain.

2. Yes, there is a separate **branch(gh-pages or not)**, but its address is different from the open web domain.

3. Was the domain separately purchased and registered?

It's just questions only for understanding.

@VitalikL if you have a lot of time for describe it, I'll be very grateful

**Comment by VitalikL** [comment]
@KeyJoo No problem.

There is folder `web` in this repository which is the main source for the `sabbath-school.adventech.io` website. During build phase the `./compile` script is executed which transforms copies all `.md` files to the this directory. We use static website framework [Hugo](https://gohugo.io) for this website. You can test it localhost by following steps:

1. Install hugo on your machine
2. Run `./compile -b test -q 2019-01 -l en` in the root directory of `sabbath-school-lessons`
3. Navigate to `web/` and run `hugo server -DF`
4. Open `localhost:1313`

**Comment by VitalikL** [comment]
@KeyJoo 

For questions 2 & 3:

2. It has nothing to do with the main website (adventech.io)
3. It is simply a subdomain which points to the compiled files

**Comment by KeyJoo** [comment]
Well that's cool. I try find more time to try it myself.

**Comment by KeyJoo** [comment]
@VitalikL for questions 3:

- what about hosting? (Is it github only?)

**Comment by VitalikL** [comment]
@KeyJoo 

`www.adventech.io` is hosted by GitHub pages (gh-pages branch)

`sabbath-school.adventech.io` is pointed to S3 bucket which is powered by AWS

**Comment by KeyJoo** [comment]
I never see before `./compile.js`. Thank you very much. :+1:
