### ISSUE TITLE
RU: Урок 2019-02/02 нерабочие ссылки в App

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-lessons#849]
# :ru: Урок 2019-02/02 :beetle: нерабочие ссылки в App

- :warning: Суббота, 6 апреля _Еккл. 2:1-11_ [проверить](https://sabbath-school.adventech.io/ru/2019-02/02/выбор-который-мыделаем/)
  - Четверг, та же ссылка
- :warning: Понедельник, 8 апреля _Пс. 118:105_  (3-й пункт) [link](https://github.com/Adventech/sabbath-school-lessons/blob/stage/src/ru/2019-02/02/03.md)
- :warning: Пятница, 12 апреля _Числ. 16:1-32_

---

## Inspected:

- Не понятно почему конвертирование Markdown произошло с ошибкой выноса за пределы списка гиперссылок
![Screenshot_2019-04-14_07-35-00__R](https://user-images.githubusercontent.com/21124057/56088379-3a687c00-5e88-11e9-8669-e8801977106f.png)

**Comment by KeyJoo** [comment]
# :dart: - Найти первопричину всех битых(не рабочих) ссылок и пофиксить

- [ ] :globe_with_meridians: исправлено

**Comment by VitalikL** [comment]
Looks like with Russian language its the chapter / verse pair of the book of Psalms. The order is different in the English Bible and the parser uses traditional versification of the book of Psalms
